#!/bin/sh
#
# Startup script for Main

APPNAME=Sonako-N2N
BASEDIR=/project/API

# MAINCLASS=
# CONFIG_FILE=$BASEDIR/config.properties
# PID_FILE=$BASEDIR/tmp/service.pid
LOG_FILE=$BASEDIR/tmp/service.log

# SERVER_PREFIX=

JVM_JDWP_PORT=8817

# JMX
#JMXHOST=
#JMXPORT=
#JMXRMIPORT=

# JVM 
XMS=300m
XMX=5000m

# java
JAVA_HOME=/usr/lib/jvm/java-11-openjdk-11.0.5.10-2.el8_1.x86_64

if [ -x $JAVA_HOME/bin/java ]; then
    JAVA=$JAVA_HOME/bin/java
else
    JAVA=`which java`
fi

# JVM_OPTS="-XX:+UseConcMarkSweepGC  -Xms$XMS  -Xmx$XMX -Djava.rmi.server.hostname=$JMXHOST -Dcom.sun.management.jmxremote.port=$JMXPORT -Dcom.sun.management.jmxremote.rmi.port=$JMXRMIPORT -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dstore_db=true -Dserver_prefix=$SERVER_PREFIX -Dserver_is_master=$MASTER -Dis_master_report=$REPORTER -Dis_serving=$SERVING -Darchaius.configurationSource.additionalUrls=file:///$CONFIG_FILE -Xdebug -Xrunjdwp:transport=dt_socket,address=$JVM_JDWP_PORT,server=y,suspend=n"

# CLASSPATH=.
# for jar in $BASEDIR/bin/*.jar; do
#     CLASSPATH=$CLASSPATH:$jar
# done

# JAVA_OPTS="$JVM_OPTS -cp $CLASSPATH $MAINCLASS"

case "$1" in
    start)
        # Main startup
        echo -n "Starting $APPNAME (port $JMXPORT): "
	exec $JAVA -jar snk_api-assembly-0.0.1-SNAPSHOT.jar > $LOG_FILE 2>&1 &
	[ ! -z $PID_FILE ] && printf "%d" $! > $PID_FILE
        echo "start OK"
        ;;
    stop)
        # Main shutdown
        echo -n "Shutdown $APPNAME: "
        kill `cat $PID_FILE`
        echo "OK"
        ;;
    reload|restart)
        $0 stop
	sleep 3
        $0 start
        ;;
    status)
        ;;
    *)
        echo "Usage: `basename $0` start|stop|restart|reload"
        exit 1
esac

exit 0
