#!/bin/sh
#
# Startup script for Main

APPNAME=Sonako-N2N
BASEDIR=/snk_deploy/snk_api

# MAINCLASS=
# CONFIG_FILE=$BASEDIR/config.properties
PID_FILE=$BASEDIR/tmp/service.pid
LOG_FILE=$BASEDIR/tmp/service.log

# SERVER_PREFIX=

JVM_JDWP_PORT=8817

# JMX
#JMXHOST=
#JMXPORT=
#JMXRMIPORT=

# JVM 
XMS=300m
XMX=5000m

# java
JAVA_HOME=/usr/lib/jvm/java-11-openjdk-11.0.5.10-2.el8_1.x86_64

if [ -x $JAVA_HOME/bin/java ]; then
    JAVA=$JAVA_HOME/bin/java
else
    JAVA=`which java`
fi

JVM_OPTS="-XX:+UseConcMarkSweepGC -Xms$XMS  -Xmx$XMX"

# CLASSPATH=.
# for jar in $BASEDIR/bin/*.jar; do
#     CLASSPATH=$CLASSPATH:$jar
# done

# JAVA_OPTS="$JVM_OPTS -cp $CLASSPATH $MAINCLASS"

case "$1" in
    start)
        # Main startup
        echo -n "Starting $APPNAME (port $JMXPORT): "
	exec $JAVA -cp snk_api-assembly-dev.0.1.jar -DPROP_FILE=application.conf com.sonako.snk_api.Main > $LOG_FILE 2>&1 &
	[ ! -z $PID_FILE ] && printf "%d" $! > $PID_FILE
        echo "start OK"
        ;;
    stop)
        # Main shutdown
        echo -n "Shutdown $APPNAME: "
        kill `cat $PID_FILE`
        echo "OK"
        ;;
    reload|restart)
        $0 stop
	sleep 3
        $0 start
        ;;
    status)
        ;;
    *)
        echo "Usage: `basename $0` start|stop|restart|reload"
        exit 1
esac

exit 0
